### ISSUE TITLE
can not use SPARK_MASTER to submit job to spark cluster

### ISSUE THREAD

**Issue by zcc1234567** [openzipkin/zipkin-dependencies#126]

**Comment by zcc1234567** [comment]
I use the command:
STORAGE_TYPE=elasticsearch ES_HOSTS=xxx ES_INDEX=monitor-zipkin SPARK_MASTER=spark://xxx:7077 java -jar ./zipkin-dependencies-2.0.5-SNAPSHOT.jar 2018-12-15

but failed.

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task serialization failed: java.lang.AssertionError: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor
java.lang.AssertionError: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor

**Comment by adriancole** [comment]
this is odd because we already have

```
                <filter>
                  <artifact>org.lz4:*</artifact>
                  <includes>
                    <include>**</include>
                  </includes>
                </filter>
```

**Comment by adriancole** [comment]
I think this might be ok now. I tried with spark 2.4.0 manually

```bash
$ ./sbin/start-master.sh; ./sbin/start-slave.sh  spark://MacBook-Pro-7.local:7077
```

```bash
$ STORAGE_TYPE=cassandra SPARK_MASTER=spark://MacBook-Pro-7.local:7077 java -jar ./main/target/zipkin-dependencies*.jar
```

I tested off master, which is being cut as 2.0.6 now
