### ISSUE TITLE
publish artifacts

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies#13]
snapshots and releases should be published to bintray etc. right now, the build fails to do that.

**Comment by adriancole** [comment]
@jamescway @abesto if either of you can rescue this, I think it is mostly ready.. just Authorization error https://travis-ci.org/openzipkin/zipkin-dependencies-spark/builds/95570721

I copied the travis and gradle config from upstream and created a bintray package zipkin-dependencies-spark

If you know the process to fix this, please log it since we've other projects not published (which I could possibly help remedy)

**Comment by abesto** [comment]
Methinks the issue is that the Bintray etc. secrets are stored as encrypted env vars, and Travis generates a unique encryption key for each project, so simply copying the relevant lines won't work. One way to fix that is to decrypt the secrets on Zipkin and re-encrypt them for this project; relevant documentation is at https://docs.travis-ci.com/user/encryption-keys/.

I'll do a step-by-step and verify with this project this week you don't get around to it / this is not enough info.

**Comment by abesto** [comment]
Some digging and our good friend StackOverflow say there's no way to decrypt the secret env variables (http://stackoverflow.com/questions/31519546/how-i-can-decrypt-secure-env-variables), so that means we need to re-encrypt all the right things.

**Comment by adriancole** [comment]
Thanks for the hints! looking at
https://github.com/openzipkin/zipkin/pull/541 I've encrypted
BINTRAY_API_KEY BINTRAY_USER, GH_USER_EMAIL, GH_USER, GH_TOKEN

Via:

```bash
$ travis encrypt BINTRAY_USER=adriancole
$ travis encrypt BINTRAY_USER=adriancole --add
$ travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
$ travis encrypt GH_USER_EMAIL=adrian.f.cole@gmail.com --add
$ travis encrypt GH_USER=adriancole --add
$ travis encrypt GH_TOKEN=XXX-travis token-XXX --add
```

**Comment by adriancole** [comment]
actually, don't use `travis encrypt ... --add` as that strips comments from file!

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-dependencies-spark/commit/3b9d27b6a563df26476db84218393568b8622c6e adds the new secrets and also avoids linting problems, ex dedupes before_install and env

**Comment by adriancole** [comment]
snapshots are now publishing, notably missing shadowJar. will look into why http://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/zipkin-dependencies-spark/1.25.3-SNAPSHOT/

**Comment by adriancole** [comment]
oh.. http://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/cassandra/1.25.3-SNAPSHOT/

we need to rename this artifact!

**Comment by adriancole** [comment]
cool.. biggie jar (just under 100MB) here! http://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/zipkin-dependencies-spark-cassandra/1.25.3-SNAPSHOT/

**Comment by adriancole** [comment]
jar checks out, albeit slow to download

**Comment by adriancole** [comment]
Attempting a release via 1.25.3 tag (to match upstream, since this is scala etc)

**Comment by adriancole** [comment]
ok that worked. just waiting for approval on maven sync

Here are the files in the mean time!
https://bintray.com/openzipkin/maven/zipkin-dependencies-spark/1.25.3/view#files

**Comment by abesto** [comment]
Great stuff, thanks!
