### ISSUE TITLE
Issue Running With Spark Cluster + Elasticsearch Storage

### ISSUE THREAD

**Issue by Vineethpp** [openzipkin/zipkin-dependencies#131]
I faced an issue in recent days, i was trying to run the dependency jar with an elasticsearch and with a spark cluster, the intention to run it with a spark cluster rather than with local[*] is to reduce the job time, but ended up with same job time even with spark cluster with one worker node. To solve and check more, i added one more spark worker to spark cluster, still the time taken by the job is same to process the same index in elasticsearch.

**Comment by adriancole** [comment]
sorry but we aren't a spark support area. no offense, we just don't know how to troubleshoot spark runtime.

you can try asking someone who knows spark to help identify what might be going wrong. https://spark.apache.org/community.html
