### ISSUE TITLE
Reminder: do NOT use the version before 2.3.0

### ISSUE THREAD

**Issue by addozhang** [openzipkin/zipkin-dependencies#149]
Before 2.3.0, the elasticsearch-spark version is 6.x which has performance issue. 

In my case, single spark job took 39 **hours** to analyze 17.8m docs(spans) (in version 2.0.1).

Now with 2.3.2, it took 27 **mins** only. 

![image](https://user-images.githubusercontent.com/2224492/64399667-e4e17580-d09b-11e9-9d20-4d08374fce29.png)

**Comment by addozhang** [comment]
I also tried zipkin-dependencies `2.0.1` with elasticsearch-spark `7.3.0`, it worked fine.

**Comment by jorgheymans** [comment]
Thanks for the note, much appreciated. if this appears on gitter or in other issues we'll link here.
