### ISSUE TITLE
Spark streaming

### ISSUE THREAD

**Issue by zxding** [openzipkin/zipkin-dependencies#153]
How to transform the project based on spark streaming? I write a demo source ,but finally I found the result is not correct when compare the result with batch process.
If I have to do so , should I translate the "DependencyLink.putTrace" logical into sparkstreaming ,now I just add mapwithstate function in sparkstreaming to aggregate the Intermediate state (parent|child).

**Comment by adriancole** [comment]
@jeqo can you point this person to your kafka streaming work? it is likely similar enough

**Comment by jeqo** [comment]
right. @zxding I'm not sure I get exactly what are you trying to achieve  here, but here are some pointer on how kafka-based storage is aggregating and building dependency links:

https://github.com/openzipkin-contrib/zipkin-storage-kafka/blob/d6f406f1becd9be834b4ec73e1aabab43028f960/storage/src/main/java/zipkin2/storage/kafka/streams/AggregationTopologySupplier.java#L72-L94

And here how it is persisted in windowed stores:

https://github.com/openzipkin-contrib/zipkin-storage-kafka/blob/d6f406f1becd9be834b4ec73e1aabab43028f960/storage/src/main/java/zipkin2/storage/kafka/streams/DependencyStoreTopologySupplier.java#L85-L104

we're following the same partitioning by `parent|child`

**Comment by zxding** [comment]
@jeqo Thank you for your quick response and I am sorry to make you confused because of my poor English.For that I think I should again describe my requirement . In our scenario, it took long(more than 1 hour) to compute the zipkin dependency , any optimization for spark conf did not work to make a near real time dependency show in batch process. So I make a little change in the source code to support spark streaming ,but perhaps the result is not correct, is any official support?

**Comment by adriancole** [comment]
currently  we aren't investing more in this job. We've found few people who
know Spark and fewer who are willing to help support this.

**Comment by jeqo** [comment]
thanks for clarifying @zxding !

That's one of the reason we are focusing on kafka-based aggregation right now. I'd assume that the sooner you want to calculate dependency links, the more inaccurate counters are. In kafka-streams we are using session windows with a heuristic timeout to determine if a trace is completed or not and supression to calculate only closed windows (ie valid traces), so we can get more accurate counters. If kafka is available on your environment, would be great if you could give a try.

**Comment by jeqo** [comment]
@zxding btw, we have released Zipkin Storage based in Kafka with support to replace [zipkin dependencies](https://github.com/openzipkin/zipkin-dependencies): https://github.com/openzipkin-contrib/zipkin-storage-kafka
