### ISSUE TITLE
I want to replace spark task with SQL

### ISSUE THREAD

**Issue by uckyk** [openzipkin/zipkin-dependencies#160]
Zipkin dependency uses spark task to calculate dependency graph. I can run it in Doris or Clickhouse through SQL when the server queries dependencies, so I don't need to build Zipkin dependency anymore. The computing power of Doris and Clickhouse is OK. But there is no idea how to write SQL. Can someone provide ideas? Thank you...

I think the spark task can still be optimized. Every time it is full computation, we can perform incremental tasks to calculate the dependency when receiving span, and then aggregate the data

**Comment by adriancole** [comment]
you can look here, but I think @jeqo's work using kafka streams is closer to the mark. eventhough it isnt using SQL to implement.

**Comment by jeqo** [comment]
These are the components to fully support dependency link query from Zipkin UI:
- aggregating spans into dependency links.
- zipkin storage implementing dependency queries.

This module supports the aggregation part for all supported databases (e.g. mysql, cassandra and elasticsearch).

If you're interested on replacing only aggregation with SQL and query results only via SQL (not by UI or API), I'd assume you already have trace spans stored in a SQL-based database--you mentioned Doris and Clickhouse. Then, I suspect you will need some kind of User-Defined Function to support aggregation as @adriancole mentioned here https://github.com/openzipkin/zipkin-dependencies/issues/161#issuecomment-576598065 --I've no personal experience with those stores to be of more help.

In case you're interested in other alternatives, there is a module that has continuous aggregation of dependencies with Kafka and Kafka Streams here: https://github.com/openzipkin-contrib/zipkin-storage-kafka#replacement-for-batch-oriented-zipkin-dependencies then you can query results by adding a SQL query engine on top of Kafka (e.g. KSQL or Presto) or downstreaming results to a SQL-based database.

**Comment by uckyk** [comment]
> These are the components to fully support dependency link query from Zipkin UI:
> 
> * aggregating spans into dependency links.
> * zipkin storage implementing dependency queries.
> 
> This module supports the aggregation part for all supported databases (e.g. mysql, cassandra and elasticsearch).
> 
> If you're interested on replacing only aggregation with SQL and query results only via SQL (not by UI or API), I'd assume you already have trace spans stored in a SQL-based database--you mentioned Doris and Clickhouse. Then, I suspect you will need some kind of User-Defined Function to support aggregation as @adriancole mentioned here [#161 (comment)](https://github.com/openzipkin/zipkin-dependencies/issues/161#issuecomment-576598065) --I've no personal experience with those stores to be of more help.
> 
> In case you're interested in other alternatives, there is a module that has continuous aggregation of dependencies with Kafka and Kafka Streams here: https://github.com/openzipkin-contrib/zipkin-storage-kafka#replacement-for-batch-oriented-zipkin-dependencies then you can query results by adding a SQL query engine on top of Kafka (e.g. KSQL or Presto) or downstreaming results to a SQL-based database.





Yes, we have already stored the data in doris(clickhouse), and we just want to replace spark calculation with sql calculation at present.
In fact, I just want to investigate whether it is possible to directly use sql to calculate dependence, because I have also read the source code and found that there is a lot of processing logic in it, and I am not sure why I write some codes like this.  So come to the community to ask if there is such a relatively mature plan.

**Comment by uckyk** [comment]
> > These are the components to fully support dependency link query from Zipkin UI:
> > 
> > * aggregating spans into dependency links.
> > * zipkin storage implementing dependency queries.
> > 
> > This module supports the aggregation part for all supported databases (e.g. mysql, cassandra and elasticsearch).
> > If you're interested on replacing only aggregation with SQL and query results only via SQL (not by UI or API), I'd assume you already have trace spans stored in a SQL-based database--you mentioned Doris and Clickhouse. Then, I suspect you will need some kind of User-Defined Function to support aggregation as @adriancole mentioned here [#161 (comment)](https://github.com/openzipkin/zipkin-dependencies/issues/161#issuecomment-576598065) --I've no personal experience with those stores to be of more help.
> > In case you're interested in other alternatives, there is a module that has continuous aggregation of dependencies with Kafka and Kafka Streams here: https://github.com/openzipkin-contrib/zipkin-storage-kafka#replacement-for-batch-oriented-zipkin-dependencies then you can query results by adding a SQL query engine on top of Kafka (e.g. KSQL or Presto) or downstreaming results to a SQL-based database.
> 
> Yes, we have already stored the data in doris(clickhouse), and we just want to replace spark calculation with sql calculation at present.
> In fact, I just want to investigate whether it is possible to directly use sql to calculate dependence, because I have also read the source code and found that there is a lot of processing logic in it, and I am not sure why I write some codes like this. So come to the community to ask if there is such a relatively mature plan.



This is the same problem, is clearer
https://github.com/openzipkin/zipkin-dependencies/issues/161

**Comment by jorgheymans** [comment]
Question answered, some suggestions on possible paths forward were given.
