### ISSUE TITLE
Dependency calculation granularity

### ISSUE THREAD

**Issue by erikbozic** [openzipkin/zipkin-dependencies#162]
Hi,
We're trying to see how the dependencies view would work for us but have ran into an issue.
While we can filter the view up to a minute and it works using the in-memory store, we can't do the same using elastic search as a store.

As far as I can tell elastic search only stores dependency data per day. There doesn't seem to be a way of for example creating an index every 10 minutes with a name reflecting that.  Then at query time I would assume zipkin would have to create an index search pattern so it would hit the correct indicies.

Is this not supported, or am I missing something?

Thank you!

**Comment by adriancole** [comment]
yes. this does daily (and some of the storage options will assume only
daily data are in there.. not entirely sure without looking). for the sake
of simplicity, this only stores daily granularity. ex the data size of the
dependencies is easy, how to reason with the cron and rerunning. the chance
of traces being incomplete only affect boundaries, so when pulling a single
day, the double-count risk isn't there as it might be with many buckets
stitched together.

there are other things around that can do arbitrary granularity, by storing
a link of each trace independently. I think this one does
https://github.com/openzipkin-contrib/zipkin-storage-kafka
https://github.com/sysco-middleware/zipkin-dependencies-streaming

**Comment by jeqo** [comment]
btw: Kafka-based storage stores dependency links in time-windows of 1 minute https://github.com/openzipkin-contrib/zipkin-storage-kafka#replacement-for-batch-oriented-zipkin-dependencies.

**Comment by erikbozic** [comment]
Thanks for the responses.
I've tried kafka storage and seems to work as expected  :)

I'll close this issue.
However I am wondering if it would be good to point this out more explicitly in the README.md.
It's mentioned here: https://github.com/openzipkin/zipkin-dependencies#usage. But it says by default, and it works when using in-memory storage...

Thanks again!
