### ISSUE TITLE
I used the crond -f as entrypoint, but that not effet,you should change the daliy shell zipkin-dependencies.jar as zipkin-dependesncies*.jar

### ISSUE THREAD

**Issue by wzyxdwll** [openzipkin/zipkin-dependencies#163]
I used the crond -f as entrypoint, but that not effet,you should change the daliy shell zipkin-dependencies.jar as zipkin-dependesncies*.jar

**Comment by adriancole** [comment]
let's use chat for questions? https://gitter.im/openzipkin/zipkin it is hard to tell if you are having trouble with the docker example or something else.

Another way is to raise a pull request for the comment you see as incorrect.

**Comment by wzyxdwll** [comment]
@adriancole ok
