### ISSUE TITLE
IllegalArgumentException: First argument must be a yyyy-MM-dd formatted date. Ex. 2016-07-16

### ISSUE THREAD

**Issue by xiaolegehaha** [openzipkin/zipkin-dependencies#173]
I started zipkin-dependencies-2.4.2.jar on Windows

The error is reported as follows:

Exception in thread "main" java.lang.IllegalArgumentException : First argument must be a yyyy-MM-dd formatted date. Ex. 2016-07-16

What should I do?

**Comment by adriancole** [comment]
you need to set environment variables same as server. ex STORAGE_TYPE

https://github.com/openzipkin/zipkin-dependencies/blob/master/README.md#usage

then when run job pass argument of date. ex. 2020-06-11 for today

**Comment by jorgheymans** [comment]
Question answered, thanks!
