### ISSUE TITLE
Bug: Periodic does not work in release Docker image

### ISSUE THREAD

**Issue by Ragin-LundF** [openzipkin/zipkin-dependencies#175]
The released Docker image copies the files with the version number (instead of the Dockerfile without release).
If the `crond` job is used, the files under /etc/periodic are depending on `zipkin-dependencies.jar` without the release number.

The Dockerfile.release only downloads one version, so it can also copy the JAR as `zipkin-dependencies.jar` for the `crond` to work.

**Comment by shakuzen** [comment]
Fixed by #175
