### ISSUE TITLE
Update image openzipkin/zipkin-dependencies:latest (2.4.1) on Docker Hub 

### ISSUE THREAD

**Issue by tomikmar** [openzipkin/zipkin-dependencies#179]
Our security scanner shows a lot of security issues with openzipkin/zipkin-dependencies:latest (=openzipkin/zipkin-dependencies:2.4.1) image. The main issue is the old version of Java 8:

    docker run -it openzipkin/zipkin-dependencies:2.4.1 bash
    bash-4.4# java -version
    openjdk version "1.8.0_212"

Could you please update?

**Comment by adriancole** [comment]
sure, we can do that.

**Comment by adriancole** [comment]
version 2.4.4 will fix this
