### ISSUE TITLE
Failed to start through docker with image version latest (2.4.4)

### ISSUE THREAD

**Issue by lllvantis** [openzipkin/zipkin-dependencies#182]
version: latest(2.4.4)

I tried to start via `docker run --env STORAGE_TYPE=elasticsearch --env ES_HOSTS=127.0.0.1:9200 openzipkin/zipkin-dependencies`
And got the result `Error: Invalid or corrupt jarfile /bin/sh`

seems something wrong with the entry point?

**Comment by adriancole** [comment]
maybe.. will look into it immediately!

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-dependencies/pull/183 should do it.. I tested it out

**Comment by lllvantis** [comment]
hash: 79323106c5d06e028d9f70f86ac73c93656f0f9b9a93f9866c25f1b8d19c7445

![Screen Shot 2020-10-17 at 16 51 19](https://user-images.githubusercontent.com/6478721/96332856-fcf63780-1098-11eb-8542-c7097a1370fc.png)
seems not working or I didn't get the real 'latest' version?

**Comment by adriancole** [comment]
Wait a bit as re-cutting latest now
