### ISSUE TITLE
It seems like crond doesn't work

### ISSUE THREAD

**Issue by SlavaUtesinov** [openzipkin/zipkin-dependencies#192]
When I start following command there is effect - `zipkin-dependency-yyyy-mm-dd` index at elasticsearch appears for a current day:

`docker run -d --env STORAGE_TYPE=elasticsearch --env ES_HOSTS=elastichost --env ES_NODES_WAN_ONLY=true openzipkin/zipkin-dependencies`

but when I start this command ([based on your example](https://github.com/openzipkin/zipkin-dependencies/tree/master/docker#cron)) there is no any effect at all even if I waiting for a long time:

`docker run -d --env STORAGE_TYPE=elasticsearch --env ES_HOSTS=elastichost  --env ES_NODES_WAN_ONLY=true --entrypoint /usr/sbin/crond openzipkin/zipkin-dependencies -f`

**Comment by shakuzen** [comment]
Looks like this is probably because the hourly/daily scripts are owned by root

**Comment by SlavaUtesinov** [comment]
I specified root user, but result is still the same i.e. absence of any result. There were logs:
```
crond[1]: crond (busybox 1.31.1) started, log level 8
crond[1]: USER root pid   6 cmd run-parts /etc/periodic/15min
crond[1]: USER root pid   7 cmd run-parts /etc/periodic/15min
```

**Comment by martin960** [comment]
Hi, thanks for the fix.
I think running as root is not ideal solution from a security perspective, but would be okay in my scenario.

**Comment by nkvaratskhelia** [comment]
Hi @jeqo, like @martin960 mentioned, running containers as root should be avoid in general. Also, I had a look at your PR and I think this point from @martin960's previous comment is still missing: "Make Scripts in /etc/periodic/ executable. - Execute permissions where missing.".
