### ISSUE TITLE
Update docker image openzipkin/zipkin-dependencies:latest (2.6.3) on Docker Hub and GitHub Container Registry

### ISSUE THREAD

**Issue by ipavlushin** [openzipkin/zipkin-dependencies#195]
## Feature
Update docker images in Docker Hub and Github registry with latest fixes from #194 

## Rationale
#194 fixes crontab file permissions in Docker image.

**Comment by nkvaratskhelia** [comment]
+1

**Comment by codefromthecrypt** [comment]
latest version is 3.0.0 and deployed to docker hub and ghcr.io supporting ES 7.x and 8.x
