### ISSUE TITLE
Docker image contains invalid cron tasks

### ISSUE THREAD

**Issue by Birthright50** [openzipkin/zipkin-dependencies#196]
Docker image contains a folder with cron tasks, https://github.com/openzipkin/zipkin-dependencies/tree/master/docker/periodic with the following content:

`java ${JAVA_OPTS} -jar /zipkin-dependencies/zipkin-dependencies.jar `date -ud yesterday +%F`` 

But the image in the `zipkin-dependencies` folder does not have this jar file.
Most likely, it should somehow repeat the launch, as indicated in the default entrypoint

**Comment by jcchavezs** [comment]
Ping @jorgheymans @jeqo @anuraaga

**Comment by nkvaratskhelia** [comment]
+1

**Comment by Birthright50** [comment]
Is the project abandoned?

**Comment by jcchavezs** [comment]
Nope. @llinder could you please check this?

**Comment by jcchavezs** [comment]
Awesome!

José Carlos Chávez


man. 4. okt. 2021 kl. 12:01 skrev Jorge Esteban Quilcate Otoya <
***@***.***>:

**Comment by jeqo** [comment]
@Birthright50 thanks for the heads-up! Fixed the release pipeline.

You can find the latest image available here: https://github.com/openzipkin/zipkin-dependencies/pkgs/container/zipkin-dependencies/8775163?tag=2.6.4

**Comment by china-zhangmy** [comment]
@jeqo 
It seems the "latest" docker image(tag=2.6.4) is not up to date align to the branch "cron".  
Files of docker/periodic/hourly/zipkin-dependencies-today & docker/periodic/daily/zipkin-dependencies-yesterday in the image don't contain the change "cd /zipkin-dependencies" before the existing command "start-zipkin-dependencies"

**Comment by chasergzy** [comment]
@china-zhangmy 
Hi, I try to use `chmod -R +x /etc/periodic/*/zipkin* ` to add execute permissions for crond files. It's worked, but also need root user.
I try to build image like this.
```
From ghcr.io/openzipkin/zipkin-dependencies
# you need to add "cd /zipkin-dependencies" before the existing command "start-zipkin-dependencies" manually 
COPY --chown=zipkin-dependencies ./zipkin-dependence/docker/periodic/ /etc/periodic/ 
RUN chmod -R +x /etc/periodic/*/zipkin* 
```
And run `docker run` with `--user root` .
