### ISSUE TITLE
Reduce the number of stages

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin-dependencies#20]
With the help of [stackoverflow](http://stackoverflow.com/questions/36322100/is-it-possible-to-read-all-rows-of-cassandra-partition-in-one-spark-worker), I managed to simplify the code significantly and remove the first two stages of M/R, that were producing nearly the same amount of output as input and causing insane disk io.

I did the change in a different (java7) repo, so I'll just post code here, until I get a chance to do a PR:

```scala
    val table: CassandraRDD[CassandraRow] = sc.cassandraTable(keyspace, "traces")

    def makeTrace(traceId: Long, rows: Iterable[CassandraRow]): Trace = {
      val spans: Map[Long, Span] = rows
        .map(rowToSpan)
        .groupBy(span => span.id)
        .mapValues(spans => spans.toList match {
          case span :: nil => span
          case head :: tail => tail.fold(head)((s1, s2) => s1.mergeSpan(s2))
          case _ => null // this can never happen
        })
        .filter(kv => kv._2.isValid)
      Trace(traceId, spans)
    }

    val aggregates: RDD[((String, String), Long)] = table
      .spanBy(row => row.getLong("trace_id"))    // read the whole partition
      .map(pair => makeTrace(pair._1, pair._2))  // and reduce it all at once, in memory
      .flatMap(_.getLinks)
      .map { case (parent, child) => ((parent, child), 1L) } // start the count
      .reduceByKey(_ + _) // add up the counts
```

**Comment by prat0318** [comment]
We are observing a large amount of /tmp disk space being filled up duing dependencies job run. The disk gets freed up after the job completion but it creates tons of disk space alerts for the machine. 

@yurishkuro do you have a rough patch that i can try out? I think that might reduce the files being written. Or in general is there a way to control the size?

**Comment by yurishkuro** [comment]
@prat0318 I had to fork this job into a private repo because I had to backport it to Java7, so I don't have a patch. But the code snipper above is essentially what needs to be changed in the job.

**Comment by adriancole** [comment]
the code is significantly different now, so please re-open if there's an opportunity to optimize stages
