### ISSUE TITLE
NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

### ISSUE THREAD

**Issue by trcoelho** [openzipkin/zipkin-dependencies#205]
Hello!

Am using zipkin-dependencies docker image as a result to build dependency on Zipkin ui.
When image starts it prints:

```
INFO CassandraDependenciesJob: Running Dependencies job for 2023-02-14: 1676332800000000 ≤ Span.timestamp 1676419199999999
WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
INFO CassandraDependenciesJob: Saving dependency links for 2023-02-14 to zipkin2.dependency

```

And then shutdown.

This is my docker-compose.yml file that I use to start zipkin-dependencies container:

```
services:
zipkin-dependencies:
    container_name: zipkin-dependencies
    image: openzipkin/zipkin-dependencies    
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_CONTACT_POINTS=localhost:9042   
      - JAVA_OPTS=-Xms8g -Xmx8g
```

Is this a bug or am I missing some additional configuration?

Zipkin server and Cassandra  3.11.14 is running on the same server by the way.

Thanks in advance.

**Comment by trcoelho** [comment]
Hi team.

Any news regarding this?
Am I missing some configuration or is this a known bug?

Thank you.

**Comment by codefromthecrypt** [comment]
please try the new examples, as they can show that this is a warning, not an error. Sorry no one got back to you earlier

https://github.com/openzipkin/zipkin-dependencies/tree/master/docker/examples
