### ISSUE TITLE
Overhaul as a java library

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies#24]
We've had a few people indicate they'd like this job to be overhauled, and some (ex @mansu @yurishkuro and I) are interested in this being a java library. As a part of this work, we can address some backlog. For example:

- [x] JRE 7 bytecode - Some users cannot run the current job due to being java 8 bytecode; Uber, for example
- [x] Java language - More users are able to help when this is written in Java. Also, core libraries are easier to use when integrated with java.
- [x] Maven - Issues like #13 are easier when this is a java library as we have a more consistent process
- [x] Less stages - The job is more efficient with less stages ex https://github.com/yurishkuro/zipkin-spark-java7
- [x] Tighter integration - we can use zipkin's java codec libraries to reduce custom code needed, as well dependency size
- [x] Elasticsearch support - Currently, this only works in cassandra, but should operate for others per #21
- [x] MySQL support - Optional, but @jcarres-mdsol and others mentioned that MySQL should have the option to return pre-aggregated dependencies, as on-demand runs out of steam quickly

**Comment by jcarres-mdsol** [comment]
Mysql support would be huge here, basically we have up on the dependency graph because it would simply timeout and never get rendered

**Comment by adriancole** [comment]
here's the java rewrite https://github.com/openzipkin/zipkin-dependencies-spark/pull/32
