### ISSUE TITLE
Rename this project to zipkin-dependencies

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies#31]
zipkin-dependencies-spark-cassandra is a mouth full, and it gets worse if we try to make a group id.

I don't expect we have resources to support anything except spark. How about if we squash the naming into zipkin-dependencies?

Ex. `io.zipkin.dependencies:zipkin-dependencies-cassandra` or `io.zipkin.dependencies:zipkin-dependencies-elasticsearch` 

Now's a great time, as I've noticed this has never actually published to maven central!

**Comment by adriancole** [comment]
ps I'd like to reserve the group id `io.zipkin.spark` for a different project, i.e. one that isn't a batch job for one screen.

**Comment by adriancole** [comment]
Note: there's some screw-up with the maven publishing, which is making it difficult to get elasticsearch published. I'd like to sort both issues at the same time.

**Comment by adriancole** [comment]
@abesto @eirslett @kristofa @michaelsembwever @yurishkuro hoping for a +1 besides me :)

**Comment by eirslett** [comment]
+1
