### ISSUE TITLE
Add JRE 7 tests

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies#41]
by installing another JRE and doing something like below, we can make sure any changes that don't work in JRE 7 break the build

https://github.com/openzipkin/zipkin/tree/master/zipkin-server/src/it/execjar

Right now, I manually test this, and rely on tools like animal sniffer and retrolambda to work properly. However, it isn't just libraries and signatures.. for example, the jar has to have less than a certain amount of files to work with JRE 7 (this is insured by shade minification). This sort of thing can only be tested by executing it.

**Comment by jorgheymans** [comment]
The minimum requirement is now 8, if there is something specific to test still to make sure this minimum JRE requirement should not be violated we should create a specific issue on this.
