### ISSUE TITLE
add support for cassandra3

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies#44]
cassandra3 is an incubating project for cassandra v3.9+

It writes a list of dependency links directly, which is nice as it no longer needs the deprecated "Dependencies" envelope type. However, parsing must be completely different as UDTs are in use.

Please remember that this project is JRE 7+ when authoring code.

**Comment by michaelsembwever** [comment]
started on this…

**Comment by adriancole** [comment]
@llinder has a scala variant here, which might be something we can port together https://github.com/SmartThingsOSS/zipkin-dependencies-cassandra3
