### ISSUE TITLE
how to config native-hadoop library

### ISSUE THREAD

**Issue by szsuyuji** [openzipkin/zipkin-dependencies#49]
# docker run -e STORAGE_TYPE=elasticsearch -e ES_CLUSTER=project-log-cluster -e JAVA_OPTS="$JAVA_OPTS -Djava.library.path=$HADOOP_HOME/lib"  -e ES_HOSTS=10.105.113.227  openzipkin/zipkin-dependencies
Processing spans from zipkin-2016-10-12/span
03:27:41.130 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Saving dependency links to zipkin-2016-10-12/dependencylink
Dependencies: []

**Comment by adriancole** [comment]
This issue was moved to openzipkin/docker-zipkin-dependencies#11
