### ISSUE TITLE
Zipkin dependencies graph with elasticstorage is not working 

### ISSUE THREAD

**Issue by ouaibsky** [openzipkin/zipkin-dependencies#50]
We used zipkin 1.12.1 (with elastic storage 1.12.1 as well) and there is no graph displayed when we click on dependencies into zipkin ui
I tried different date range without any success.

Ir works fine when using in memory storage, is it supposed to work with elastic ?

Thx
Christophe

**Comment by adriancole** [comment]
did you try running the zipkin-dependencies job in the README (via java -jar or docker?) what did it output?

**Comment by ouaibsky** [comment]
Nop, i'll do the test and keep you in touch

**Comment by abhijitvk** [comment]
@adriancole - I am facing a similar issue. On my local set up, I have Spring cloud with Zipkin version of 1.19.2, zipkin-autoconfigure-storage-elasticsearch-http#1.19.2  and Elastic Search v 5.4.0. 

When using in memory storage, the trace of calls are shown fine for gateway and application services and it also shows dependencies. 

When I use elastic storage, I see the correct trace only when I select gateway service. However the trace doesn't show in the application service. Is this expected behavior? Nothing shows in dependencies tab, also tried running the fat jar, it doesn't move beyond the first 2 lines

STORAGE_TYPE=elasticsearch ES_HOSTS=localhost:9200 ZIPKIN_LOG_LEVEL=DEBUG java -jar zipkin-dependencies-1.5.4.jar
17/05/09 14:17:27 INFO ElasticsearchDependenciesJob: Processing spans from zipkin-2017-05-09/span
17/05/09 14:17:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

@ouaibsky : Were you able to test yours successfully?

**Comment by adriancole** [comment]
please go to https://gitter.im/openzipkin/zipkin for general
troubleshooting as issues are for code changes to this repo

**Comment by ouaibsky** [comment]
@abhijitvk tested on windows and got this error:
```
C:\Users\clalleme\Downloads>java -jar zipkin-dependencies-1.5.4.jar
17/05/10 10:47:39 INFO ElasticsearchDependenciesJob: Processing spans from onyx-zipkin-2017-05-10/span
17/05/10 10:47:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java cl
asses where applicable
17/05/10 10:47:42 INFO ElasticsearchDependenciesJob: Saving dependency links to zipkin-2017-05-10/dependencylink
[Stage 0:>                                                          (0 + 5) / 5]17/05/10 10:47:43 ERROR Shell: Failed to
 locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:278)
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:300)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:293)
        at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:867)

blabla
```

**Comment by ouaibsky** [comment]
under Linux, better but no result even if log tell me it should get something.
Testing with zipkin-ui for this index and there is some span.
file **zipkin-2017-05-10/dependencylink** doesn't exist

Regards
Christophe

```
17/05/10 10:54:56 INFO ElasticsearchDependenciesJob: Processing spans from zipkin-2017-05-10/span
17/05/10 10:54:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/05/10 10:55:02 INFO ElasticsearchDependenciesJob: Saving dependency links to zipkin-2017-05-10/dependencylink
17/05/10 10:55:11 INFO ElasticsearchDependenciesJob: Done
```

**Comment by adriancole** [comment]
probably should open a separate issue for windows.

if there was no DEBUG output then no spans were found for that day

**Comment by ouaibsky** [comment]
As i said, indexed are full of span
Terminal display some information like this below, but disappear at end of job
Is there some option to turn on debug information ?

17/05/10 11:35:01 INFO ElasticsearchDependenciesJob: Processing spans from onyx-zipkin-2017-05-09/span
17/05/10 11:35:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/05/10 11:35:04 INFO ElasticsearchDependenciesJob: Saving dependency links to onyx-zipkin-2017-05-09/dependencylink
[Stage 0:===========>                                               (1 + 4) / 5]

**Comment by adriancole** [comment]
ZIPKIN_LOG_LEVEL=DEBUG should emit log lines for each trace found. If you don't see that, we can't proceed. 

ps as mentioned before https://gitter.im/openzipkin/zipkin is for troubleshooting. issues are for changes to the codebase. please stop replying here unless there's an actual code change needed.

**Comment by ouaibsky** [comment]
With debug option I got a bunch of messages telling me processing is ok.
But no file is generated into current dir (/tmp)
Unfortunately my company's proxy refused connection to https://gitter.im.

```
17/05/10 12:20:33 INFO ElasticsearchDependenciesJob: Processing spans from onyx-zipkin-2017-05-09/span
17/05/10 12:20:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/05/10 12:20:36 INFO ElasticsearchDependenciesJob: Saving dependency links to onyx-zipkin-2017-05-09/dependencylink
^M[Stage 0:>                                                          (0 + 0) / 5]^M[Stage 0:>                                                          (0 + 5) / 5]^M[Stage 0:=======================>                                   (2 + 3) / 5]^M[Stage 1:>                                                          (0 + 5) / 5]17/05/10 12:20:48 DEBUG DependencyLinker: traversing trace tree, breadth-first
17/05/10 12:20:48 DEBUG DependencyLinker: processing {"traceId": "1870875d3cbb109e", "id": "1870875d3cbb109e", "kind": "UNKNOWN"}
17/05/10 12:20:48 DEBUG DependencyLinker: non-rpc span; skipping
...
17/05/10 12:17:54 DEBUG DependencyLinker: traversing trace tree, breadth-first
17/05/10 12:17:54 DEBUG DependencyLinker: processing {"traceId": "aaca91adc12c092f", "id": "aaca91adc12c092f", "kind": "SERVER", "service": "onyx-request"}
17/05/10 12:17:54 DEBUG DependencyLinker: root's peer is unknown; skipping
17/05/10 12:17:54 DEBUG DependencyLinker: traversing trace tree, breadth-first
17/05/10 12:17:54 DEBUG DependencyLinker: processing {"traceId": "611221642c6f99b2", "id": "611221642c6f99b2", "kind": "UNKNOWN"}
17/05/10 12:17:54 DEBUG DependencyLinker: non-rpc span; skipping
17/05/10 12:17:54 DEBUG DependencyLinker: processing {"traceId": "95f80caaf148f545", "parentId": "257e78c47d04776f", "id": "ac12cebda680494b", "kind": "SERVER", "service": "onyx-risky", "peerService": "onyx-workflow"}
17/05/10 12:17:54 DEBUG DependencyLinker: incrementing link onyx-workflow -> onyx-risky
17/05/10 12:17:54 DEBUG DependencyLinker: traversing trace tree, breadth-first
... 
^M                                                                                ^M17/05/10 12:20:57 INFO ElasticsearchDependenciesJob: Done

```

**Comment by ouaibsky** [comment]
Looks like now in zipkin ui dependencies rendering is working :+1:

**Comment by adriancole** [comment]
ok thanks for letting me know about your proxy. Appreciate your trying.

Glad you are back in business!

**Comment by vgurikar** [comment]
How did you fix it. Im facing a similar issue

**Comment by adriancole** [comment]
this issue has been more or less a collection of different things. closing it in favor of gitter or stackoverflow.

**Comment by koushik9951** [comment]
I am trying to generate the dependency graph using spark, But dependency jar is not distributing to more than 1 worker machine. even after adding another worker node also.

can someone look into this issue?

**Comment by adriancole** [comment]
no one knows spark here. it is better to enlist someone who does

**Comment by adriancole** [comment]
for general spark support, please can try asking someone who knows spark to help identify what might be going wrong. https://spark.apache.org/community.html

Adding to closed issues won't get you closer to a solution. Just trying to save you from waiting here for no reason.

**Comment by RITH10th** [comment]
Hello

**Comment by RITH10th** [comment]
Can u help me to solve the problem that I cannot search Dependency graph in zipkin dashboard
