### ISSUE TITLE
Spark job memory leak detected

### ISSUE THREAD

**Issue by fabioranfi** [openzipkin/zipkin-dependencies#55]
Hi
I'm running Zipkin-dependencies on Elasticsearch storage, I have between 8M and 9M span a day, and while running dependency in early morning gives no error, later I start having failures.
Looks like the high memory usage while scaling with data is the main problem.

I'm running Zipkin version 1.16.0.
Elasticsearch v. 2.3.3
I collected logs from Zipkin-dependencies both v. 1.3.0 and v. 1.2.0.

[zipkin-dep_1.2.0.txt](https://github.com/openzipkin/zipkin-dependencies/files/606094/zipkin-dep_1.2.0.txt)
[zipkin-dep_1.3.0.txt](https://github.com/openzipkin/zipkin-dependencies/files/606095/zipkin-dep_1.3.0.txt)

What should be a nice setup for Java heap?
Thank you.

**Comment by adriancole** [comment]
hard to say what the best heap would be, as it depends on what those 8-9M
turn into. If I were you, I'd bump the heap as high as practical, maybe
with -verbose:gc and trim down from there. At some point, you might need to
use a spark cluster, but overprovisioning with a large VM might get you by
until then.

**Comment by fabioranfi** [comment]
Thank you Adrian, the problem is I'm running it inside a Mesos cluster, so I cannot take so many resources. It looks like the only way to go is to run it in early morning when the dataset is smaller.

**Comment by adriancole** [comment]
ps there may be other ways to accomplish this, too. for example, possibly the job could fetch less data at a time and merge it together

**Comment by fabioranfi** [comment]
Do you know how can I do it in release 1.3? I didn't see options like this, it still starts fetching data from midnight, maybe you mean it could be in a future release

**Comment by adriancole** [comment]
I mean a future release as I don't actually know how to do this, but I suspect it is possible!
