### ISSUE TITLE
How to  use zipkin-dependencies

### ISSUE THREAD

**Issue by tomgithub2016** [openzipkin/zipkin-dependencies#61]
In my project ,I used  STORAGE_TYPE=cassandra for Zipkin

`Step 1: `
         I'm sure the trace  data was stored in the table  zipkin.traces of Cassandra  and  I can use  the` Find Traces function` of Zipkin（http://localhost:9411）  to query and Zipkin was displayed  the trace data in the Web UI.
 
`Step 2: `
  Depend on` Step 1`, I want to use zipkin-dependencies to run Cassandra Dependencies Job 

First:
` I was Setting environment variables        STORAGE_TYPE=cassandra`
Second:
execute ` java -jar zipkin-dependencies-1.4.0.jar`  in windows cmd terminal 
The cmd  terminal displays as follows:
```
Running Dependencies job for 2017-02-15: 1487116800000000 ≤ Span.timestamp 1487203199999999
16:04:58.870 [main] WARN  com.datastax.driver.core.NettyUtil - Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
Saving with day=2017-02-15
Done
```
I think the operation was completed
`Step 3: `
  I  use Zipkin of `Analyze Dependencies` function (http://localhost:9411/dependency?endTs=1487149655421&startTs=1487063255422) to query  ,but there was no data to display on Page UI.(empty)
```
So:
My question 1:
     Is this the right way to use  zipkin-dependencies-1.4.0.jar
```

```
question 2:
    CassandraDependenciesJob.class  run is done, Why I use Analyze Dependencies function of Zipkin to query ,the result is empty?

```

**Comment by tomgithub2016** [comment]
And In the table  zipkin.dependencies  of  Cassandra,There was a data as follows:

 ```
day                      | dependencies
--------------------------+------------------------------------------------------------------
 2017-02-15 00:00:00+0000 | 0x0a00010000015a3f1190000a00020000015a3f1190000f00030c0000000000

(1 rows)
```

**Comment by adriancole** [comment]
>
> Running Dependencies job for 2017-02-15: 1487116800000000 ≤ Span.timestamp 1487203199999999
>
> so take off the right-most 3 numbers and you get unix time. 1487116800000
1487203199999

> I use Zipkin of Analyze Dependencies function (http://localhost:9411/
> dependency?endTs=1487149655421&startTs=1487063255422) to query ,but there
> was no data to display on Page UI.(empty)
>
The UI isn't searching the same time.. can you change the URL to
http://localhost:9411/dependency?endTs=
<http://localhost:9411/dependency?endTs=1487149655421&startTs=1487063255422>
1487203199999&startTs=1487116800000

Also this only works if the dependencies job actually found any links.
There could be missing links if the data in zipkin isn't associated
properly. Anyway first step is to align the time of your query just in case.

**Comment by tomgithub2016** [comment]
@adriancole   If I use brave api to demo serviceA call service B,and run zipkin-dependency , I can query the
data in dependencies UI Page.
But as same as Service A call Service B to User Brave-opentracing, I can not query the data in dependencies UI Page.

**Comment by tomgithub2016** [comment]
@adriancole 
If I use  OkHttpClient   On ServiceA as Client  and use BraveServletFilter on ServiceB as Server,　ServiceA call ServiceB ,and run zipkin-dependency ,In the table zipkin.dependencies of Cassandra,There was a data as follows:    I can query the data in dependencies UI Page.
```
 day                      | dependencies
--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------
  2017-02-16 00:00:00+0000 | 0x0a00010000015a4437ec000a00020000015a4437ec000f00030c000000010b00010000000873657276696365310b00020000000873657276696365320a000400000000000000010000
```

But If I use Brave-opentracing API On ServiceA

```
	Span span1 = opentracing.buildSpan("Span1").withTag(Constants.LOCAL_COMPONENT, "client").start();
		brave.Span braveSpan = ((BraveSpan) span1).unwrap();
		braveSpan.kind(Kind.CLIENT);
		
		//braveSpan.annotate(Constants.CLIENT_SEND);

		Map<String, String> map = new LinkedHashMap<>();
		TextMapInjectAdapter carrier = new TextMapInjectAdapter(map);
		opentracing.inject(span1.context(), Format.Builtin.HTTP_HEADERS, carrier);
		System.out.println(map);
		ResponseEntity<String> rs = null;
		try
		{
			HttpHeaders header = new HttpHeaders();
			header.setAll(map);
			HttpEntity entity = new HttpEntity(header);
			//rs = restTemplate.postForEntity("http://localhost:9191/Service2", new HttpEntity(header), String.class);

						rs = restTemplate.postForEntity("http://localhost:9191/extract2",
								new HttpEntity(header), String.class);
			
			//braveSpan.annotate(Constants.SERVER_ADDR);
		}
		catch (Exception e)
		{
			String excepiton = e.getMessage();
			//braveSpan.annotate(excepiton);
			braveSpan.tag("excepiton", excepiton);
		}
		finally
		{
			if (rs != null)
			{
				int httpStatusValue = rs.getStatusCodeValue();
				braveSpan.tag("http.status_code", String.valueOf(httpStatusValue));
 			}
			
			braveSpan.finish();
		}

		return "Service A Finish";
```

 use Brave-opentracing API On ServiceB 


```
	String traceId = request.getHeader("X-B3-TraceId");
		String spanId = request.getHeader("X-B3-SpanId");
		String sampleId = request.getHeader("X-B3-Sampled");
		String parentSpanId = request.getHeader("X-B3-ParentSpanId");

		Map<String, String> map = new LinkedHashMap<>();
		map.put("X-B3-TraceId", traceId);
		map.put("X-B3-SpanId", spanId);
		map.put("X-B3-Sampled", sampleId);

		BraveSpanContext openTracingContext = (BraveSpanContext) opentracing.extract(Format.Builtin.HTTP_HEADERS,
				new TextMapExtractAdapter(map));
		//        
		Span span2 = opentracing.buildSpan("Span2").withTag(Constants.LOCAL_COMPONENT, "Service-B")
				.asChildOf(opentracing.extract(Format.Builtin.HTTP_HEADERS, new TextMapExtractAdapter(map)))
				.withTag("http.url", basePath).start();

		brave.Span braveSpan = ((BraveSpan) span2).unwrap();
		braveSpan.kind(Kind.SERVER);
		 
		try
		{
			Thread.sleep(2000);
			 
			 
		}
		catch (InterruptedException e)
		{
			e.printStackTrace();
		}
		braveSpan.finish();

		return "Service B finish";
```


and run zipkin-dependency ,In the table zipkin.dependencies of Cassandra,There was a data as follows: I can not  query the data in dependencies UI Page.

 ```
day                      | dependencies
--------------------------+----------------------------------------------------------------------------------------
 2017-02-15 00:00:00+0000 |                                                                                  0x0a00010000015a3f1190000a00020000015a3f1190000f00030c0000000000

```

Different ways of implementation，Zipkin-dependencies running different results,Why?

Opentracing way 's  dependencies is `0x0a00010000015a3f1190000a00020000015a3f1190000f00030c0000000000`，this length less than 
`0x0a00010000015a4437ec000a00020000015a4437ec000f00030c000000010b00010000000873657276696
`
Can you help me to analysis the reason?

**Comment by adriancole** [comment]
This issue was moved to openzipkin/brave-opentracing#20
