### ISSUE TITLE
Zipkin dependency job fails with Elasticsearch 5 storage

### ISSUE THREAD

**Issue by hardit** [openzipkin/zipkin-dependencies#67]
I set up Zipkin (docker image: openzipkin/zipkin:1.22.0) with Elasticsearch storage (v 5.3.0). The traces were generated with [zipkin-js-example](https://github.com/openzipkin/zipkin-js-example) service. Zipkin UI works fine and shows the traces.

But running zipkin-dependencies jobs fails (docker image: openzipkin/zipkin-dependencies:1.5.0) - with message "Failed to parse request body"

Zipkin dependency logs attached:
[zipkin-test-dependencies-logs-20170411.txt](https://github.com/openzipkin/zipkin-dependencies/files/912475/zipkin-test-dependencies-logs-20170411.txt)

**Comment by adriancole** [comment]
try 1.5.2? this code uses the elasticsearch driver directly and likely that needs to be at or above the version in use

**Comment by hardit** [comment]
The [docker-zipkin-dependencies](https://github.com/openzipkin/docker-zipkin-dependencies) 1.5.2 build has been [failed](https://travis-ci.org/openzipkin/docker-zipkin-dependencies/branches). 
Is it possible to retry the build of the container with zipkin-dependencies 1.5.2. 

If not, then I can download the 1.5.2 jar and try to build it into a container myself

**Comment by adriancole** [comment]
hmm looks like the build trigger didn't fire. I restarted it and clicked
the trigger manually in quay. interesting as we had a similar problem on
the upstream zipkin image (only zipkin had a problem, not the others like
zipkin-mysql shrug..)

https://travis-ci.org/openzipkin/docker-zipkin-dependencies/builds/219585656

**Comment by hardit** [comment]
Thanks Adrian,
I got the zipkin-dependencies container 1.5.2 from the dockerhub. 
The zipkin+dependencies container was working well with the zipkin-js-example traces and with my own traces also.

![screen shot 2017-04-12 at 13 17 25](https://cloud.githubusercontent.com/assets/1445789/24953278/5b717672-1f83-11e7-8ad9-3e72897693ab.png)

**Comment by adriancole** [comment]
good news! thanks for replying back

**Comment by adriancole** [comment]
@bsideup if bored some time... wanna port our ES tests to use testcontainers? I think our docker elasticsearch5 should track latest. Interestingly ES java driver seems to need version parity of some sort (ex needed to bump client to 5.3 to support cluster running 5.3)
