### ISSUE TITLE
Add support to draw external dependencies

### ISSUE THREAD

**Issue by kubagruszka** [openzipkin/zipkin-dependencies#71]
As far as I can see zipkin-dependencies can't draw the dependencies outgoing from a mesh of the fully instrumented services. To give an example I have suite of java (dropwizard) based microservices that are instrumented with brave by jax-rs instrumentation of the container and client filters. The zipkin-dependencies is able to draw nice graph on dependencies between those service but it doesn't show the external dependencies which they rely on even though the jax-rs client is also instrumented so a span for that traffic is created as well. It would be nice to draw this kind of blocks on that dependency graph so we could have better insights on the actual integrations.

**Comment by adriancole** [comment]
This is a general question about dependencies (logic on this is actually in the main zipkin project). The normal way to accomplish this is via the "sa" annotation, automatically added in many zipkin instrumentation projects like zipkin-js and brave when appropriate setup is in place.

Ex. in brave, it is `.clientOf("server-name")` https://github.com/openzipkin/brave/tree/master/instrumentation#custom-configuration

in zipkin-js, it is remoteServerName
https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin-instrumentation-cujojs-rest#usage

Here's the actual doc on the "sa" binary annotation:
https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L232
