### ISSUE TITLE
Bad malformed data

### ISSUE THREAD

**Issue by jprateekvmware** [openzipkin/zipkin-dependencies#72]
Hi All,
Getting the issues , attached in the image.
Do we have option to ignore the bad data while processing , rather than going and having the bad data fixed.
if that would be the case it would be very helpfull.

![image](https://cloud.githubusercontent.com/assets/21043786/26808226/3946f0c4-4a10-11e7-9cc2-fb2d81a648a2.png)

**Comment by adriancole** [comment]
can you try latest? An error at that line doesn't make sense with current
code

**Comment by adriancole** [comment]
this hasn't been updated to latest zipkin code yet. standby

**Comment by adriancole** [comment]
can you try latest (not release, snapshot)?

**Comment by jprateekvmware** [comment]
Working fine , thank you so much adrian
