### ISSUE TITLE
fails security scan

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin-dependencies#76]
There are a number of vulnerabilities in zipkin-dependencies which our security team has raised.
These should hopefully be resolved by dependency bumping

![1](https://user-images.githubusercontent.com/28124884/28147443-d849a93e-67c3-11e7-8bd0-62dfe03fae5e.png)
![2](https://user-images.githubusercontent.com/28124884/28147442-d846a798-67c3-11e7-96ac-1454721f76fc.png)

**Comment by sirtyro** [comment]
CC'ing @fedj  @michaelsembwever @ImFlog @ys @adriancole

**Comment by sirtyro** [comment]
Happy to take this on as a PR, but given how unfamiliar i am with the code, some guidance or suggestions around any versions that shouldn't go too high would be appreciated.

**Comment by adriancole** [comment]
Maybe open a separate issue to raise minumum version to spark 2.2 (scala
2.11 hadoop 2.7+)

The reason for holding this back formerly was uber's hadoop install. Since
uber are jaeger now this is no longer oir burden. If no-one screams, we can
update to the higher versions next week (you can play now)

If this goes we could follow suit with zipkin-sparkstreaming cc @mansu

**Comment by ys** [comment]
Happy to give it a try when bumped!

**Comment by adriancole** [comment]
made an issue highlighting spark version upgrade #77

**Comment by sirtyro** [comment]
So I had a look at this and pretty much all the questionable dependencies are coming from spark core. So it's not as simple as I had hoped. I bumped to scala_version 2.11 and spark 2.2 which has seen some of the questionable dependencies version bumped. 

I was hoping there would be other dependencies I could bump other than just spark-core.

**Comment by adriancole** [comment]
>
> I was hoping there would be other dependencies I could bump other than
> just spark-core.
>
so, are you saying there are still dodgy dependencies after spark 2.2? or
are you saying it isn't as much work as you were hoping for? :)

**Comment by sirtyro** [comment]
More that it isn't going to work as I had hoped.

Usually, with these issues in-house, we go to the project and bump a bunch of dependencies. But in this case, they all stem from spark. So, there's not much that can be done in isolation to https://github.com/openzipkin/zipkin-dependencies/issues/77

**Comment by adriancole** [comment]
currently things are bumped to spark 2.1 (2.2 isn't compatible w/cassandra yet)

**Comment by jorgheymans** [comment]
Cute, did not know `ghost` is the placeholder for user accounts that get deleted.
