### ISSUE TITLE
Unable to find spans

### ISSUE THREAD

**Issue by ccwillia** [openzipkin/zipkin-dependencies#89]
I am using the ElasticsearchHttpStorage for zipkins.  I can see my zipkins index created but when i run the zipkins-dependencies jar its unable to find spans.

17/08/22 21:21:01 INFO ElasticsearchDependenciesJob: No spans found at zipkin-2017-08-22/span
17/08/22 21:21:01 INFO ElasticsearchDependenciesJob: Processing spans from zipkin:span-2017-08-22/span
17/08/22 21:21:01 INFO ElasticsearchDependenciesJob: No spans found at zipkin:span-2017-08-22/span

Here is the command i am executing

STORAGE_TYPE=elasticsearch ES_HOSTS=http://*******:9200,http://******:9200 ES_INDEX=zipkin ES_USERNAME=**** ES_PASSWORD=***** java -Djava.security.egd=file:/dev/./urandom -jar zipkin-dependencies.jar

**Comment by adriancole** [comment]
There should be two sets of lines, one with :span and one without. The
dependencies job checks for two types of indexes. We check both to make
sure migrations work.

the latter style with :span will be the default in zipkin 1.31
https://github.com/openzipkin/zipkin/pull/1698

I can see how the message could be alarming..

**Comment by ccwillia** [comment]
I am running zipkin 1.31, but when i run the dependency job its not able to find any spans.  I have tried adding ES_EXPERIMENTAL_SPAN2=true and ES_LEGACY_READS_ENABLED=false

**Comment by adriancole** [comment]
can you set `ZIPKIN_LOG_LEVEL=DEBUG` and see if it is skipping traces?

**Comment by ccwillia** [comment]
It looks like every trace is being skip as they all have the following entries after them

17/08/24 14:18:51 DEBUG DependencyLinker: root's peer is unknown; skipping
17/08/24 14:18:51 DEBUG DependencyLinker: traversing trace tree, breadth-first

**Comment by adriancole** [comment]
probably best to get json from one of your traces. by that log it seems
none are connected (all root spans). might be easier to help debug on
gitter https://gitter.im/openzipkin/zipkin

**Comment by lyb914231042** [comment]
how to solve this problem？

**Comment by jaspers1203** [comment]
I also got "non remote span; skipping", and result show No dependency links could be processed from spans in index zipkin-span-2019-09-19, who can tell me what is the trouble? thx

19/09/19 13:48:32 DEBUG DependencyLinker: traversing trace tree, breadth-first
19/09/19 13:48:32 DEBUG DependencyLinker: processing {"traceId":"14bf578cfeaae8b7749906e0f918f501","id":"290a2e1d7bc330aa","name":"start","timestamp":1568900791998356,"duration":31976,"localEndpoint":{"serviceName":"hello_world","ipv4":"192.168.0.105","port":8080},"tags":{"lc":"hello_world"},"debug":true}
19/09/19 13:48:32 DEBUG DependencyLinker: non remote span; skipping
19/09/19 13:48:32 DEBUG DependencyLinker: processing {"traceId":"14bf578cfeaae8b7749906e0f918f501","parentId":"290a2e1d7bc330aa","id":"12c6c7ec36a2ccce","name":"hello","timestamp":1568900792001337,"duration":1998,"localEndpoint":{"serviceName":"hello","ipv4":"192.168.0.105","port":7702},"annotations":[{"timestamp":1568900792001337,"value":"step=service1"}],"tags":{"lc":"Hello"},"debug":true}
19/09/19 13:48:32 DEBUG DependencyLinker: non remote span; skipping
19/09/19 13:48:32 DEBUG DependencyLinker: processing {"traceId":"14bf578cfeaae8b7749906e0f918f501","parentId":"12c6c7ec36a2ccce","id":"25031297aa37e76a","name":"world","timestamp":1568900792002350,"duration":1,"localEndpoint":{"serviceName":"world","ipv4":"192.168.0.105","port":7703},"annotations":[{"timestamp":1568900792002350,"value":"step=rpcx"}],"tags":{"lc":"World","method":"Hello"},"debug":true}
19/09/19 13:48:32 DEBUG DependencyLinker: non remote span; skipping
19/09/19 13:48:32 INFO ElasticsearchDependenciesJob: No dependency links could be processed from spans in index zipkin:span-2019-09-19/span
19/09/19 13:48:32 INFO ElasticsearchDependenciesJob: Processing spans from zipkin-span-2019-09-19
19/09/19 13:48:33 INFO ElasticsearchDependenciesJob: No dependency links could be processed from spans in index zipkin-span-2019-09-19
19/09/19 13:48:33 INFO ElasticsearchDependenciesJob: Done

**Comment by jaspers1203** [comment]
btw, zipkin2.16.2, es6.8/7.3 dependencies2.3.0

**Comment by adriancole** [comment]
It looks like you are generating ad-hoc data. The dependencies job is only
for remote spans (client, server, producer, consumer). Please try a working
example like https://github.com/openzipkin/sleuth-webmvc-example

Also, please follow-up on https://gitter.im/openzipkin/zipkin as we don't
use issues for exploratory questions.

**Comment by jaspers1203** [comment]
a lots thanks Adrian, i am a newer in zipkin, and create the tracing by golang & rpcx, how can I modify the span structure with remote span model? I use context metadata to transfer parent span to child by tracer inject & extract (opentracing.TextMapCarrier)

**Comment by adriancole** [comment]
@jaspers1203 I think you missed this part

> please follow-up on https://gitter.im/openzipkin/zipkin as we don't
use issues for exploratory questions.

**Comment by jaspers1203** [comment]
@adriancole yes I get that, have a good day~

**Comment by jorgheymans** [comment]
Question answered, closing.
